-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pixup-3A
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pixup-3A` ;

-- -----------------------------------------------------
-- Schema pixup-3A
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pixup-3A` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `pixup-3A` ;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_ESTADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_ESTADO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_ESTADO` (
  `iD` INT NOT NULL AUTO_INCREMENT,
  `ESTADO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iD`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_MUNICIPIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_MUNICIPIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_MUNICIPIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MUNICIPIO` VARCHAR(45) NOT NULL,
  `TBL_ESTADO_iD` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_MUNICIPIO_TBL_ESTADO`
    FOREIGN KEY (`TBL_ESTADO_iD`)
    REFERENCES `pixup-3A`.`TBL_ESTADO` (`iD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_MUNICIPIO_TBL_ESTADO_idx` ON `pixup-3A`.`TBL_MUNICIPIO` (`TBL_ESTADO_iD` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_ARTISTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_ARTISTA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_ARTISTA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ARTISTA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_DISQUERA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_DISQUERA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_DISQUERA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DISQUERA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_GENEROMUSICAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_GENEROMUSICAL` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_GENEROMUSICAL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `GENEROMUSICAL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_DISCO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_DISCO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_DISCO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(200) NOT NULL,
  `PRECIO` FLOAT NOT NULL,
  `EXISTENCIA` INT NOT NULL,
  `DESCUENTO` FLOAT NOT NULL,
  `FECHA_LANZAMIENTO` DATE NOT NULL,
  `IMAGEN` VARCHAR(120) NOT NULL,
  `TBL_DISQUERA_ID` INT NOT NULL,
  `TBL_ARTISTA_ID` INT NOT NULL,
  `TBL_GENEROMUSICAL_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_DISCO_TBL_GENEROMUSICAL1`
    FOREIGN KEY (`TBL_GENEROMUSICAL_ID`)
    REFERENCES `pixup-3A`.`TBL_GENEROMUSICAL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DISCO_TBL_DISQUERA1`
    FOREIGN KEY (`TBL_DISQUERA_ID`)
    REFERENCES `pixup-3A`.`TBL_DISQUERA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DISCO_TBL_ARTISTA1`
    FOREIGN KEY (`TBL_ARTISTA_ID`)
    REFERENCES `pixup-3A`.`TBL_ARTISTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DISCO_TBL_GENEROMUSICAL1_idx` ON `pixup-3A`.`TBL_DISCO` (`TBL_GENEROMUSICAL_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DISCO_TBL_DISQUERA1_idx` ON `pixup-3A`.`TBL_DISCO` (`TBL_DISQUERA_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DISCO_TBL_ARTISTA1_idx` ON `pixup-3A`.`TBL_DISCO` (`TBL_ARTISTA_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_CANCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_CANCION` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_CANCION` (
  `ID` INT NOT NULL,
  `TITULO` VARCHAR(45) NOT NULL,
  `DURACION` TIME NOT NULL,
  `TBL_DISCO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_CANCION_TBL_DISCO1`
    FOREIGN KEY (`TBL_DISCO_ID`)
    REFERENCES `pixup-3A`.`TBL_DISCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_CANCION_TBL_DISCO1_idx` ON `pixup-3A`.`TBL_CANCION` (`TBL_DISCO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_USUARIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `PRIMER_APELLIDO` VARCHAR(45) NOT NULL,
  `SEGUNDO_APELLIDO` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(150) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `RFC` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_ORDEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_ORDEN` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_ORDEN` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COSTO_TOTAL` FLOAT NOT NULL,
  `FECHA` TIMESTAMP NOT NULL,
  `CANTIDAD_TOTAL` INT NOT NULL,
  `ESTATUS_ENVIO` TINYINT NOT NULL,
  `COSTO_ENVIO` FLOAT NOT NULL,
  `TBL_USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_ORDEN_TBL_USUARIO1`
    FOREIGN KEY (`TBL_USUARIO_ID`)
    REFERENCES `pixup-3A`.`TBL_USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_ORDEN_TBL_USUARIO1_idx` ON `pixup-3A`.`TBL_ORDEN` (`TBL_USUARIO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_PAGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_PAGO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_PAGO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NUMERO_TARJETA` VARCHAR(45) NOT NULL,
  `MONTO` FLOAT NOT NULL,
  `FECHA` TIMESTAMP NOT NULL,
  `TBL_ORDEN_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_PAGO_TBL_ORDEN1`
    FOREIGN KEY (`TBL_ORDEN_ID`)
    REFERENCES `pixup-3A`.`TBL_ORDEN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_PAGO_TBL_ORDEN1_idx` ON `pixup-3A`.`TBL_PAGO` (`TBL_ORDEN_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_DETALLE_ORDEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_DETALLE_ORDEN` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_DETALLE_ORDEN` (
  `TBL_DISCO_ID` INT NOT NULL,
  `TBL_ORDEN_ID` INT NOT NULL,
  `CANTIDAD` INT NOT NULL,
  `COSTO` FLOAT NOT NULL,
  PRIMARY KEY (`TBL_DISCO_ID`, `TBL_ORDEN_ID`),
  CONSTRAINT `fk_TBL_DETALLE_ORDEN_TBL_ORDEN1`
    FOREIGN KEY (`TBL_ORDEN_ID`)
    REFERENCES `pixup-3A`.`TBL_ORDEN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DETALLE_ORDEN_TBL_DISCO1`
    FOREIGN KEY (`TBL_DISCO_ID`)
    REFERENCES `pixup-3A`.`TBL_DISCO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DETALLE_ORDEN_TBL_DISCO1_idx` ON `pixup-3A`.`TBL_DETALLE_ORDEN` (`TBL_DISCO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_COLONIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_COLONIA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_COLONIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COLONIA` VARCHAR(45) NOT NULL,
  `CP` VARCHAR(45) NOT NULL,
  `TBL_MUNICIPIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_COLONIA_TBL_MUNICIPIO1`
    FOREIGN KEY (`TBL_MUNICIPIO_ID`)
    REFERENCES `pixup-3A`.`TBL_MUNICIPIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_COLONIA_TBL_MUNICIPIO1_idx` ON `pixup-3A`.`TBL_COLONIA` (`TBL_MUNICIPIO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_TIPO_DOMICILIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_TIPO_DOMICILIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_TIPO_DOMICILIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_DOMICILIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_DOMICILIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_DOMICILIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CALLE` VARCHAR(45) NOT NULL,
  `NUM_EXTERIOR` VARCHAR(45) NOT NULL,
  `NUM_INTERIOR` VARCHAR(45) NOT NULL,
  `TBL_USUARIO_ID` INT NOT NULL,
  `TBL_COLONIA_ID` INT NOT NULL,
  `TBL_TIPO_DOMICILIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_DOMICILIO_TBL_COLONIA1`
    FOREIGN KEY (`TBL_COLONIA_ID`)
    REFERENCES `pixup-3A`.`TBL_COLONIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DOMICILIO_TBL_TIPO_DOMICILIO1`
    FOREIGN KEY (`TBL_TIPO_DOMICILIO_ID`)
    REFERENCES `pixup-3A`.`TBL_TIPO_DOMICILIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_DOMICILIO_TBL_USUARIO1`
    FOREIGN KEY (`TBL_USUARIO_ID`)
    REFERENCES `pixup-3A`.`TBL_USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DOMICILIO_TBL_COLONIA1_idx` ON `pixup-3A`.`TBL_DOMICILIO` (`TBL_COLONIA_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DOMICILIO_TBL_TIPO_DOMICILIO1_idx` ON `pixup-3A`.`TBL_DOMICILIO` (`TBL_TIPO_DOMICILIO_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_DOMICILIO_TBL_USUARIO1_idx` ON `pixup-3A`.`TBL_DOMICILIO` (`TBL_USUARIO_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_TIPO_NOTIFICACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_TIPO_NOTIFICACION` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_TIPO_NOTIFICACION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(45) NOT NULL,
  `RUTA_PLANTILLA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pixup-3A`.`TBL_NOTIFICACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pixup-3A`.`TBL_NOTIFICACION` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pixup-3A`.`TBL_NOTIFICACION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FECHA_NOTIFICACION` DATETIME NOT NULL,
  `TBL_USUARIO_ID` INT NOT NULL,
  `TBL_TIPO_NOTIFICACION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_TBL_NOTIFICACION_TBL_TIPO_NOTIFICACION1`
    FOREIGN KEY (`TBL_TIPO_NOTIFICACION_ID`)
    REFERENCES `pixup-3A`.`TBL_TIPO_NOTIFICACION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_NOTIFICACION_TBL_USUARIO1`
    FOREIGN KEY (`TBL_USUARIO_ID`)
    REFERENCES `pixup-3A`.`TBL_USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_NOTIFICACION_TBL_TIPO_NOTIFICACION1_idx` ON `pixup-3A`.`TBL_NOTIFICACION` (`TBL_TIPO_NOTIFICACION_ID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_TBL_NOTIFICACION_TBL_USUARIO1_idx` ON `pixup-3A`.`TBL_NOTIFICACION` (`TBL_USUARIO_ID` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
